name: Publish Helm chart

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Chart Version
        run: |
          echo "VERSION=$(awk -F': *' '/^[[:space:]]*version:/ {print $2; exit}' charts/Chart.yaml)" >> $GITHUB_ENV

    #   - name: Publish to gh-pages
    #     uses: stefanprodan/helm-gh-pages@v1.7.0
    #     env:
    #       TMPDIR: /tmp
    #     with:
    #       token: ${{ secrets.GITHUB_TOKEN }}
    #       charts_dir: .

      - name: Publish OCI chart to GHCR
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: puls8-headlamp
          repository: abhinandan-purkait/puls8/dev/helm
          tag: ${{ env.VERSION }}
          path: ./charts
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
