name: Release Docker image

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/abhinandan-purkait/puls8-headlamp-plugin/dev/puls8-headlamp-plugin:latest
            ghcr.io/abhinandan-purkait/puls8-headlamp-plugin/dev/puls8-headlamp-plugin:${{ github.ref_name }}

    #   - name: Log in to Dockerhub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.REGISTRY_USERNAME }}
    #       password: ${{ secrets.REGISTRY_PASSWORD }}

    #   - name: Build and push image
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       platforms: linux/amd64,linux/arm64
    #       push: true
    #       tags: |
    #         docker.io/datacoresoftware/puls8-headlamp-plugin:latest
    #         docker.io/datacoresoftware/puls8-headlamp-plugin:${{ github.ref_name }}
