name: Release Plugin

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      RELEASE_DIR: artifacts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Make script executable
        run: chmod +x scripts/release.sh

      - name: Build and package with script
        run: ./scripts/release.sh release --release-dir "${RELEASE_DIR}"

      - name: Upload assets to the GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.RELEASE_DIR }}/*.tar.gz
          fail_on_unmatched_files: true
          generate_release_notes: false
